### ISSUE TITLE
Add a visible list of hotkeys

### ISSUE THREAD

**Issue by vanjasmailovic** [julianxhokaxhiu/chrome-deezer-mediakeys-reloaded#6]
Sometimes I forget what the hotkeys are and it would be very useful to have these listed somewhere, without having to figure out to press "H" every time. :grin:

**Comment by julianxhokaxhiu** [comment]
Actually the hotkeys are the well known mediakeys present in each keyboard or laptop :) There is no need to know them, unless you override them. Then it's up to you to learn them :D

Also, as I'm using native Chromium functionality to provide them, this looks like to me a feature request to Chromium team rather than to this extension :)

But thanks for the tip anyway. Cheers.
